# Generated by Django 5.2.1 on 2025-06-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_status",
            field=models.CharField(
                blank=True, default="unpaid", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
