# Generated by Django 5.2.1 on 2025-05-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_rename_priview_course_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="courses/privileges"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="courses/lesson_previews"
            ),
        ),
    ]
